//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace no.geointegrasjon.rep.matrikkelfoering {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Adresse", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class AdresseType {
        
        private string adressekodeField;
        
        private string adressenavnField;
        
        private string adressenummerField;
        
        private string adressebokstavField;
        
        private string seksjonsnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adressekode {
            get {
                return this.adressekodeField;
            }
            set {
                this.adressekodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adressenavn {
            get {
                return this.adressenavnField;
            }
            set {
                this.adressenavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adressenummer {
            get {
                return this.adressenummerField;
            }
            set {
                this.adressenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adressebokstav {
            get {
                return this.adressebokstavField;
            }
            set {
                this.adressebokstavField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string seksjonsnummer {
            get {
                return this.seksjonsnummerField;
            }
            set {
                this.seksjonsnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class Koordinat {
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        private bool zFieldSpecified;
        
        /// <remarks/>
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        public double z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zSpecified {
            get {
                return this.zFieldSpecified;
            }
            set {
                this.zFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class Ring {
        
        private Koordinat[] lukketKurveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("liste", IsNullable=false)]
        public Koordinat[] lukketKurve {
            get {
                return this.lukketKurveField;
            }
            set {
                this.lukketKurveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KoordinatsystemKode))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Kodeliste/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Kodeliste/xml.schema/2012.01.31", IsNullable=false)]
    public partial class Kode {
        
        private string kodeverdiField;
        
        private string kodebeskrivelseField;
        
        private bool erGyldigField;
        
        private bool erGyldigFieldSpecified;
        
        /// <remarks/>
        public string kodeverdi {
            get {
                return this.kodeverdiField;
            }
            set {
                this.kodeverdiField = value;
            }
        }
        
        /// <remarks/>
        public string kodebeskrivelse {
            get {
                return this.kodebeskrivelseField;
            }
            set {
                this.kodebeskrivelseField = value;
            }
        }
        
        /// <remarks/>
        public bool erGyldig {
            get {
                return this.erGyldigField;
            }
            set {
                this.erGyldigField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool erGyldigSpecified {
            get {
                return this.erGyldigFieldSpecified;
            }
            set {
                this.erGyldigFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class KoordinatsystemKode : Kode {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bbox))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Punkt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Kurve))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Flate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class Geometri {
        
        private KoordinatsystemKode koordinatsystemField;
        
        /// <remarks/>
        public KoordinatsystemKode koordinatsystem {
            get {
                return this.koordinatsystemField;
            }
            set {
                this.koordinatsystemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class Bbox : Geometri {
        
        private Koordinat nedreVenstreField;
        
        private Koordinat oevreHoeyreField;
        
        /// <remarks/>
        public Koordinat nedreVenstre {
            get {
                return this.nedreVenstreField;
            }
            set {
                this.nedreVenstreField = value;
            }
        }
        
        /// <remarks/>
        public Koordinat oevreHoeyre {
            get {
                return this.oevreHoeyreField;
            }
            set {
                this.oevreHoeyreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class Punkt : Geometri {
        
        private Koordinat posisjonField;
        
        /// <remarks/>
        public Koordinat posisjon {
            get {
                return this.posisjonField;
            }
            set {
                this.posisjonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class Kurve : Geometri {
        
        private Koordinat[] linjeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("liste", IsNullable=false)]
        public Koordinat[] linje {
            get {
                return this.linjeField;
            }
            set {
                this.linjeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class Flate : Geometri {
        
        private Ring[] indreAvgrensningField;
        
        private Ring ytreAvgrensningField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("liste", IsNullable=false)]
        public Ring[] indreAvgrensning {
            get {
                return this.indreAvgrensningField;
            }
            set {
                this.indreAvgrensningField = value;
            }
        }
        
        /// <remarks/>
        public Ring ytreAvgrensning {
            get {
                return this.ytreAvgrensningField;
            }
            set {
                this.ytreAvgrensningField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Avloepstilknytning", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class AvloepstilknytningType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Bruksenhet", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class BruksenhetType {
        
        private BruksenhetsnummerType bruksenhetsnummerField;
        
        private BruksenhetstypeKodeType bruksenhetstypeField;
        
        private System.Nullable<double> bruksarealField;
        
        private bool bruksarealFieldSpecified;
        
        private KjoekkentilgangKodeType kjoekkentilgangField;
        
        private string antallRomField;
        
        private string antallBadField;
        
        private string antallWCField;
        
        private AdresseType adresseField;
        
        private MatrikkelnummerType matrikkelnummerField;
        
        private EndringsstatusType endringField;
        
        /// <remarks/>
        public BruksenhetsnummerType bruksenhetsnummer {
            get {
                return this.bruksenhetsnummerField;
            }
            set {
                this.bruksenhetsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BruksenhetstypeKodeType bruksenhetstype {
            get {
                return this.bruksenhetstypeField;
            }
            set {
                this.bruksenhetstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bruksareal {
            get {
                return this.bruksarealField;
            }
            set {
                this.bruksarealField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruksarealSpecified {
            get {
                return this.bruksarealFieldSpecified;
            }
            set {
                this.bruksarealFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public KjoekkentilgangKodeType kjoekkentilgang {
            get {
                return this.kjoekkentilgangField;
            }
            set {
                this.kjoekkentilgangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string antallRom {
            get {
                return this.antallRomField;
            }
            set {
                this.antallRomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string antallBad {
            get {
                return this.antallBadField;
            }
            set {
                this.antallBadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string antallWC {
            get {
                return this.antallWCField;
            }
            set {
                this.antallWCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AdresseType adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrikkelnummerType matrikkelnummer {
            get {
                return this.matrikkelnummerField;
            }
            set {
                this.matrikkelnummerField = value;
            }
        }
        
        /// <remarks/>
        public EndringsstatusType endring {
            get {
                return this.endringField;
            }
            set {
                this.endringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Bruksenhetsnummer", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class BruksenhetsnummerType {
        
        private EtasjeplanType etasjeplanField;
        
        private string etasjenummerField;
        
        private string loepenummerField;
        
        /// <remarks/>
        public EtasjeplanType etasjeplan {
            get {
                return this.etasjeplanField;
            }
            set {
                this.etasjeplanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string etasjenummer {
            get {
                return this.etasjenummerField;
            }
            set {
                this.etasjenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string loepenummer {
            get {
                return this.loepenummerField;
            }
            set {
                this.loepenummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Etasjeplan", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class EtasjeplanType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("BruksenhetstypeKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class BruksenhetstypeKodeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("KjoekkentilgangKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class KjoekkentilgangKodeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Matrikkelnummer", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class MatrikkelnummerType {
        
        private string kommunenummerField;
        
        private string gaardsnummerField;
        
        private string bruksnummerField;
        
        private string festenummerField;
        
        private string seksjonsnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kommunenummer {
            get {
                return this.kommunenummerField;
            }
            set {
                this.kommunenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string gaardsnummer {
            get {
                return this.gaardsnummerField;
            }
            set {
                this.gaardsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string bruksnummer {
            get {
                return this.bruksnummerField;
            }
            set {
                this.bruksnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string festenummer {
            get {
                return this.festenummerField;
            }
            set {
                this.festenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string seksjonsnummer {
            get {
                return this.seksjonsnummerField;
            }
            set {
                this.seksjonsnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    public enum EndringsstatusType {
        
        /// <remarks/>
        Eksisterende,
        
        /// <remarks/>
        Ny,
        
        /// <remarks/>
        Endret,
        
        /// <remarks/>
        Fjernet,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Byggesak", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class ByggesakType {
        
        private string systemIdField;
        
        private string tittelField;
        
        private SaksnummerType saksnummerField;
        
        private ProsesskategoriType kategoriField;
        
        private TiltaktypeType[] tiltakstypeField;
        
        private VedtakType vedtakField;
        
        private PartType ansvarligSoekerField;
        
        private PartType tiltakshaverField;
        
        private MatrikkelopplysningerType matrikkelopplysningerField;
        
        private string adresseField;
        
        private SaksnummerType[] referanseAndreSakerField;
        
        private SaksnummerType[] referanseKlagesakerField;
        
        private System.DateTime registrertDatoField;
        
        private string saksbehandlerField;
        
        private Punkt posisjonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public SaksnummerType saksnummer {
            get {
                return this.saksnummerField;
            }
            set {
                this.saksnummerField = value;
            }
        }
        
        /// <remarks/>
        public ProsesskategoriType kategori {
            get {
                return this.kategoriField;
            }
            set {
                this.kategoriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tiltaktype", IsNullable=false)]
        public TiltaktypeType[] tiltakstype {
            get {
                return this.tiltakstypeField;
            }
            set {
                this.tiltakstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VedtakType vedtak {
            get {
                return this.vedtakField;
            }
            set {
                this.vedtakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PartType ansvarligSoeker {
            get {
                return this.ansvarligSoekerField;
            }
            set {
                this.ansvarligSoekerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PartType tiltakshaver {
            get {
                return this.tiltakshaverField;
            }
            set {
                this.tiltakshaverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrikkelopplysningerType matrikkelopplysninger {
            get {
                return this.matrikkelopplysningerField;
            }
            set {
                this.matrikkelopplysningerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("saksnummer", IsNullable=false)]
        public SaksnummerType[] referanseAndreSaker {
            get {
                return this.referanseAndreSakerField;
            }
            set {
                this.referanseAndreSakerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("saksnummer", IsNullable=false)]
        public SaksnummerType[] referanseKlagesaker {
            get {
                return this.referanseKlagesakerField;
            }
            set {
                this.referanseKlagesakerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime registrertDato {
            get {
                return this.registrertDatoField;
            }
            set {
                this.registrertDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string saksbehandler {
            get {
                return this.saksbehandlerField;
            }
            set {
                this.saksbehandlerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Punkt posisjon {
            get {
                return this.posisjonField;
            }
            set {
                this.posisjonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Saksnummer", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class SaksnummerType {
        
        private string saksaarField;
        
        private string sakssekvensnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string saksaar {
            get {
                return this.saksaarField;
            }
            set {
                this.saksaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string sakssekvensnummer {
            get {
                return this.sakssekvensnummerField;
            }
            set {
                this.sakssekvensnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Prosesskategori", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class ProsesskategoriType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Tiltaktype", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class TiltaktypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Vedtak", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class VedtakType {
        
        private string beskrivelseField;
        
        private System.DateTime vedtaksdatoField;
        
        private VedtakstypeType statusField;
        
        private DispensasjonType[] dispensasjonerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime vedtaksdato {
            get {
                return this.vedtaksdatoField;
            }
            set {
                this.vedtaksdatoField = value;
            }
        }
        
        /// <remarks/>
        public VedtakstypeType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dispensasjon", IsNullable=false)]
        public DispensasjonType[] dispensasjoner {
            get {
                return this.dispensasjonerField;
            }
            set {
                this.dispensasjonerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Vedtakstype", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class VedtakstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Dispensasjon", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class DispensasjonType {
        
        private DispensasjonstypeType dispensasjonstypeField;
        
        private string begrunnelseField;
        
        /// <remarks/>
        public DispensasjonstypeType dispensasjonstype {
            get {
                return this.dispensasjonstypeField;
            }
            set {
                this.dispensasjonstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string begrunnelse {
            get {
                return this.begrunnelseField;
            }
            set {
                this.begrunnelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Dispensasjonstype", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class DispensasjonstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Part", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class PartType {
        
        private PartstypeType partstypeField;
        
        private string foedselsnummerField;
        
        private string organisasjonsnummerField;
        
        private string navnField;
        
        private EnkelAdresseType adresseField;
        
        private string telefonnummerField;
        
        private string mobilnummerField;
        
        private string epostField;
        
        /// <remarks/>
        public PartstypeType partstype {
            get {
                return this.partstypeField;
            }
            set {
                this.partstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string foedselsnummer {
            get {
                return this.foedselsnummerField;
            }
            set {
                this.foedselsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string organisasjonsnummer {
            get {
                return this.organisasjonsnummerField;
            }
            set {
                this.organisasjonsnummerField = value;
            }
        }
        
        /// <remarks/>
        public string navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EnkelAdresseType adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string telefonnummer {
            get {
                return this.telefonnummerField;
            }
            set {
                this.telefonnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mobilnummer {
            get {
                return this.mobilnummerField;
            }
            set {
                this.mobilnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string epost {
            get {
                return this.epostField;
            }
            set {
                this.epostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Partstype", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class PartstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("EnkelAdresse", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class EnkelAdresseType {
        
        private string adresselinje1Field;
        
        private string adresselinje2Field;
        
        private string adresselinje3Field;
        
        private string postnrField;
        
        private string poststedField;
        
        private string landkodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje1 {
            get {
                return this.adresselinje1Field;
            }
            set {
                this.adresselinje1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje2 {
            get {
                return this.adresselinje2Field;
            }
            set {
                this.adresselinje2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje3 {
            get {
                return this.adresselinje3Field;
            }
            set {
                this.adresselinje3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string postnr {
            get {
                return this.postnrField;
            }
            set {
                this.postnrField = value;
            }
        }
        
        /// <remarks/>
        public string poststed {
            get {
                return this.poststedField;
            }
            set {
                this.poststedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string landkode {
            get {
                return this.landkodeField;
            }
            set {
                this.landkodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Matrikkelopplysninger", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class MatrikkelopplysningerType {
        
        private MatrikkelnummerType[] eiendomsidentifikasjonField;
        
        private AdresseType[] adresseField;
        
        private BygningType[] bygningField;
        
        private System.Nullable<System.DateTime> oppdatertDatoField;
        
        private bool oppdatertDatoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("matrikkelnummer", IsNullable=false)]
        public MatrikkelnummerType[] eiendomsidentifikasjon {
            get {
                return this.eiendomsidentifikasjonField;
            }
            set {
                this.eiendomsidentifikasjonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("adresse", IsNullable=false)]
        public AdresseType[] adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("bygning", IsNullable=false)]
        public BygningType[] bygning {
            get {
                return this.bygningField;
            }
            set {
                this.bygningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> oppdatertDato {
            get {
                return this.oppdatertDatoField;
            }
            set {
                this.oppdatertDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oppdatertDatoSpecified {
            get {
                return this.oppdatertDatoFieldSpecified;
            }
            set {
                this.oppdatertDatoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Bygning", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class BygningType {
        
        private string bygningsnummerField;
        
        private NaeringsgruppeType naeringsgruppeField;
        
        private BygningstypeType bygningstypeField;
        
        private System.Nullable<double> bebygdArealField;
        
        private bool bebygdArealFieldSpecified;
        
        private BruksenhetType[] bruksenheterField;
        
        private EtasjeType[] etasjerField;
        
        private AvloepstilknytningType avlopField;
        
        private EnergiforsyningType energiforsyningField;
        
        private VanntilknytningType vannforsyningField;
        
        private System.Nullable<bool> harHeisField;
        
        private bool harHeisFieldSpecified;
        
        private EndringsstatusType endringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bygningsnummer {
            get {
                return this.bygningsnummerField;
            }
            set {
                this.bygningsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NaeringsgruppeType naeringsgruppe {
            get {
                return this.naeringsgruppeField;
            }
            set {
                this.naeringsgruppeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BygningstypeType bygningstype {
            get {
                return this.bygningstypeField;
            }
            set {
                this.bygningstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bebygdAreal {
            get {
                return this.bebygdArealField;
            }
            set {
                this.bebygdArealField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bebygdArealSpecified {
            get {
                return this.bebygdArealFieldSpecified;
            }
            set {
                this.bebygdArealFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("bruksenhet", IsNullable=false)]
        public BruksenhetType[] bruksenheter {
            get {
                return this.bruksenheterField;
            }
            set {
                this.bruksenheterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("etasje", IsNullable=false)]
        public EtasjeType[] etasjer {
            get {
                return this.etasjerField;
            }
            set {
                this.etasjerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AvloepstilknytningType avlop {
            get {
                return this.avlopField;
            }
            set {
                this.avlopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EnergiforsyningType energiforsyning {
            get {
                return this.energiforsyningField;
            }
            set {
                this.energiforsyningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VanntilknytningType vannforsyning {
            get {
                return this.vannforsyningField;
            }
            set {
                this.vannforsyningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> harHeis {
            get {
                return this.harHeisField;
            }
            set {
                this.harHeisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool harHeisSpecified {
            get {
                return this.harHeisFieldSpecified;
            }
            set {
                this.harHeisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public EndringsstatusType endring {
            get {
                return this.endringField;
            }
            set {
                this.endringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Naeringsgruppe", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class NaeringsgruppeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Bygningstype", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class BygningstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Etasje", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class EtasjeType {
        
        private string etasjenummerField;
        
        private EtasjeplanType etasjeplanField;
        
        private string antallBoenheterField;
        
        private System.Nullable<double> bruksarealTilAnnetField;
        
        private bool bruksarealTilAnnetFieldSpecified;
        
        private System.Nullable<double> bruksarealTilBoligField;
        
        private bool bruksarealTilBoligFieldSpecified;
        
        private System.Nullable<double> bruksarealTotaltField;
        
        private bool bruksarealTotaltFieldSpecified;
        
        private System.Nullable<double> bruttoarealTilBoligField;
        
        private bool bruttoarealTilBoligFieldSpecified;
        
        private System.Nullable<double> bruttoarealTotaltField;
        
        private bool bruttoarealTotaltFieldSpecified;
        
        private System.Nullable<double> bruttoarealTilAnnetField;
        
        private bool bruttoarealTilAnnetFieldSpecified;
        
        private EndringsstatusType endringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string etasjenummer {
            get {
                return this.etasjenummerField;
            }
            set {
                this.etasjenummerField = value;
            }
        }
        
        /// <remarks/>
        public EtasjeplanType etasjeplan {
            get {
                return this.etasjeplanField;
            }
            set {
                this.etasjeplanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string antallBoenheter {
            get {
                return this.antallBoenheterField;
            }
            set {
                this.antallBoenheterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bruksarealTilAnnet {
            get {
                return this.bruksarealTilAnnetField;
            }
            set {
                this.bruksarealTilAnnetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruksarealTilAnnetSpecified {
            get {
                return this.bruksarealTilAnnetFieldSpecified;
            }
            set {
                this.bruksarealTilAnnetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bruksarealTilBolig {
            get {
                return this.bruksarealTilBoligField;
            }
            set {
                this.bruksarealTilBoligField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruksarealTilBoligSpecified {
            get {
                return this.bruksarealTilBoligFieldSpecified;
            }
            set {
                this.bruksarealTilBoligFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bruksarealTotalt {
            get {
                return this.bruksarealTotaltField;
            }
            set {
                this.bruksarealTotaltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruksarealTotaltSpecified {
            get {
                return this.bruksarealTotaltFieldSpecified;
            }
            set {
                this.bruksarealTotaltFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bruttoarealTilBolig {
            get {
                return this.bruttoarealTilBoligField;
            }
            set {
                this.bruttoarealTilBoligField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruttoarealTilBoligSpecified {
            get {
                return this.bruttoarealTilBoligFieldSpecified;
            }
            set {
                this.bruttoarealTilBoligFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bruttoarealTotalt {
            get {
                return this.bruttoarealTotaltField;
            }
            set {
                this.bruttoarealTotaltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruttoarealTotaltSpecified {
            get {
                return this.bruttoarealTotaltFieldSpecified;
            }
            set {
                this.bruttoarealTotaltFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bruttoarealTilAnnet {
            get {
                return this.bruttoarealTilAnnetField;
            }
            set {
                this.bruttoarealTilAnnetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruttoarealTilAnnetSpecified {
            get {
                return this.bruttoarealTilAnnetFieldSpecified;
            }
            set {
                this.bruttoarealTilAnnetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public EndringsstatusType endring {
            get {
                return this.endringField;
            }
            set {
                this.endringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Energiforsyning", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class EnergiforsyningType {
        
        private VarmefordelingType[] varmefordelingField;
        
        private EnergiforsyningTypeType[] energiforsyningField;
        
        private System.Nullable<bool> relevantField;
        
        private bool relevantFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("varmefordeling", IsNullable=false)]
        public VarmefordelingType[] varmefordeling {
            get {
                return this.varmefordelingField;
            }
            set {
                this.varmefordelingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("energiforsyningType", IsNullable=false)]
        public EnergiforsyningTypeType[] energiforsyning {
            get {
                return this.energiforsyningField;
            }
            set {
                this.energiforsyningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> relevant {
            get {
                return this.relevantField;
            }
            set {
                this.relevantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool relevantSpecified {
            get {
                return this.relevantFieldSpecified;
            }
            set {
                this.relevantFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Varmefordeling", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class VarmefordelingType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("EnergiforsyningType", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class EnergiforsyningTypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Vanntilknytning", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class VanntilknytningType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class KoordinatsystemKodeListe {
        
        private KoordinatsystemKode[] listeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("liste")]
        public KoordinatsystemKode[] liste {
            get {
                return this.listeField;
            }
            set {
                this.listeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class FlateListe {
        
        private Flate[] listeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("liste")]
        public Flate[] liste {
            get {
                return this.listeField;
            }
            set {
                this.listeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class KoordinatListe {
        
        private Koordinat[] listeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("liste")]
        public Koordinat[] liste {
            get {
                return this.listeField;
            }
            set {
                this.listeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class PunktListe {
        
        private Punkt[] listeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("liste")]
        public Punkt[] liste {
            get {
                return this.listeField;
            }
            set {
                this.listeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class RingListe {
        
        private Ring[] listeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("liste")]
        public Ring[] liste {
            get {
                return this.listeField;
            }
            set {
                this.listeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class BboxListe {
        
        private Bbox[] listeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("liste")]
        public Bbox[] liste {
            get {
                return this.listeField;
            }
            set {
                this.listeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class OmraadeListe {
        
        private Omraade[] listeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("liste")]
        public Omraade[] liste {
            get {
                return this.listeField;
            }
            set {
                this.listeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", IsNullable=false)]
    public partial class Omraade {
        
        private Punkt punktField;
        
        private Flate flateField;
        
        /// <remarks/>
        public Punkt punkt {
            get {
                return this.punktField;
            }
            set {
                this.punktField = value;
            }
        }
        
        /// <remarks/>
        public Flate flate {
            get {
                return this.flateField;
            }
            set {
                this.flateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Kodeliste/xml.schema/2012.01.31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Kodeliste/xml.schema/2012.01.31", IsNullable=false)]
    public partial class KodeListe {
        
        private Kode[] listeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("liste")]
        public Kode[] liste {
            get {
                return this.listeField;
            }
            set {
                this.listeField = value;
            }
        }
    }
}
