//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace no.geointegrasjon.rep.matrikkelfoering {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Adresse", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class AdresseType {
        
        private string adressekodeField;
        
        private string adressenavnField;
        
        private string adressenummerField;
        
        private string adressebokstavField;
        
        private string seksjonsnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adressekode {
            get {
                return this.adressekodeField;
            }
            set {
                this.adressekodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adressenavn {
            get {
                return this.adressenavnField;
            }
            set {
                this.adressenavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adressenummer {
            get {
                return this.adressenummerField;
            }
            set {
                this.adressenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adressebokstav {
            get {
                return this.adressebokstavField;
            }
            set {
                this.adressebokstavField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string seksjonsnummer {
            get {
                return this.seksjonsnummerField;
            }
            set {
                this.seksjonsnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Avloepstilknytning", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class AvloepstilknytningType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Boligadresse", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class BoligadresseType {
        
        private string adressekodeField;
        
        private string adressenavnField;
        
        private string adressenummerField;
        
        private string adressebokstavField;
        
        private string seksjonsnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adressekode {
            get {
                return this.adressekodeField;
            }
            set {
                this.adressekodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adressenavn {
            get {
                return this.adressenavnField;
            }
            set {
                this.adressenavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adressenummer {
            get {
                return this.adressenummerField;
            }
            set {
                this.adressenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adressebokstav {
            get {
                return this.adressebokstavField;
            }
            set {
                this.adressebokstavField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string seksjonsnummer {
            get {
                return this.seksjonsnummerField;
            }
            set {
                this.seksjonsnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Bruksenhet", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class BruksenhetType {
        
        private BruksenhetsnummerType bruksenhetsnummerField;
        
        private System.Nullable<double> bruksarealField;
        
        private bool bruksarealFieldSpecified;
        
        private KjoekkentilgangKodeType kjoekkentilgangField;
        
        private string antallRomField;
        
        private string antallBadField;
        
        private string antallWCField;
        
        private BruksenhetstypeKodeType bruksenhetstypeField;
        
        private BoligadresseType adresseField;
        
        private EndringsstatusType endringField;
        
        private MatrikkelnummerType matrikkelnummerField;
        
        /// <remarks/>
        public BruksenhetsnummerType bruksenhetsnummer {
            get {
                return this.bruksenhetsnummerField;
            }
            set {
                this.bruksenhetsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bruksareal {
            get {
                return this.bruksarealField;
            }
            set {
                this.bruksarealField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruksarealSpecified {
            get {
                return this.bruksarealFieldSpecified;
            }
            set {
                this.bruksarealFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public KjoekkentilgangKodeType kjoekkentilgang {
            get {
                return this.kjoekkentilgangField;
            }
            set {
                this.kjoekkentilgangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string antallRom {
            get {
                return this.antallRomField;
            }
            set {
                this.antallRomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string antallBad {
            get {
                return this.antallBadField;
            }
            set {
                this.antallBadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string antallWC {
            get {
                return this.antallWCField;
            }
            set {
                this.antallWCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BruksenhetstypeKodeType bruksenhetstype {
            get {
                return this.bruksenhetstypeField;
            }
            set {
                this.bruksenhetstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BoligadresseType adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        public EndringsstatusType endring {
            get {
                return this.endringField;
            }
            set {
                this.endringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrikkelnummerType matrikkelnummer {
            get {
                return this.matrikkelnummerField;
            }
            set {
                this.matrikkelnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Bruksenhetsnummer", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class BruksenhetsnummerType {
        
        private EtasjeplanType etasjeplanField;
        
        private string etasjenummerField;
        
        private string loepenummerField;
        
        /// <remarks/>
        public EtasjeplanType etasjeplan {
            get {
                return this.etasjeplanField;
            }
            set {
                this.etasjeplanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string etasjenummer {
            get {
                return this.etasjenummerField;
            }
            set {
                this.etasjenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string loepenummer {
            get {
                return this.loepenummerField;
            }
            set {
                this.loepenummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Etasjeplan", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class EtasjeplanType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("KjoekkentilgangKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class KjoekkentilgangKodeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("BruksenhetstypeKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class BruksenhetstypeKodeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    public enum EndringsstatusType {
        
        /// <remarks/>
        Eksisterende,
        
        /// <remarks/>
        Ny,
        
        /// <remarks/>
        Endret,
        
        /// <remarks/>
        Fjernet,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Matrikkelnummer", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class MatrikkelnummerType {
        
        private string kommunenummerField;
        
        private string gaardsnummerField;
        
        private string bruksnummerField;
        
        private string festenummerField;
        
        private string seksjonsnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kommunenummer {
            get {
                return this.kommunenummerField;
            }
            set {
                this.kommunenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string gaardsnummer {
            get {
                return this.gaardsnummerField;
            }
            set {
                this.gaardsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string bruksnummer {
            get {
                return this.bruksnummerField;
            }
            set {
                this.bruksnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string festenummer {
            get {
                return this.festenummerField;
            }
            set {
                this.festenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string seksjonsnummer {
            get {
                return this.seksjonsnummerField;
            }
            set {
                this.seksjonsnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Byggesak", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class ByggesakType {
        
        private string adresseField;
        
        private MatrikkelopplysningerType matrikkelopplysningerField;
        
        private SaksnummerType[] referanseAndreSakerField;
        
        private SaksnummerType[] referanseKlagesakerField;
        
        private System.DateTime registrertDatoField;
        
        private SaksnummerType saksnummerField;
        
        private string systemIdField;
        
        private VedtakType vedtakField;
        
        private string tittelField;
        
        private TiltaktypeType[] tiltakstypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrikkelopplysningerType matrikkelopplysninger {
            get {
                return this.matrikkelopplysningerField;
            }
            set {
                this.matrikkelopplysningerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("saksnummer", IsNullable=false)]
        public SaksnummerType[] referanseAndreSaker {
            get {
                return this.referanseAndreSakerField;
            }
            set {
                this.referanseAndreSakerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("saksnummer", IsNullable=false)]
        public SaksnummerType[] referanseKlagesaker {
            get {
                return this.referanseKlagesakerField;
            }
            set {
                this.referanseKlagesakerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime registrertDato {
            get {
                return this.registrertDatoField;
            }
            set {
                this.registrertDatoField = value;
            }
        }
        
        /// <remarks/>
        public SaksnummerType saksnummer {
            get {
                return this.saksnummerField;
            }
            set {
                this.saksnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VedtakType vedtak {
            get {
                return this.vedtakField;
            }
            set {
                this.vedtakField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tiltaktype", IsNullable=false)]
        public TiltaktypeType[] tiltakstype {
            get {
                return this.tiltakstypeField;
            }
            set {
                this.tiltakstypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Matrikkelopplysninger", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class MatrikkelopplysningerType {
        
        private MatrikkelnummerType[] eiendomsidentifikasjonField;
        
        private AdresseType[] adresseField;
        
        private BygningType[] bygningField;
        
        private System.Nullable<System.DateTime> oppdatertDatoField;
        
        private bool oppdatertDatoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("matrikkelnummer", IsNullable=false)]
        public MatrikkelnummerType[] eiendomsidentifikasjon {
            get {
                return this.eiendomsidentifikasjonField;
            }
            set {
                this.eiendomsidentifikasjonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("adresse", IsNullable=false)]
        public AdresseType[] adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("bygning", IsNullable=false)]
        public BygningType[] bygning {
            get {
                return this.bygningField;
            }
            set {
                this.bygningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> oppdatertDato {
            get {
                return this.oppdatertDatoField;
            }
            set {
                this.oppdatertDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oppdatertDatoSpecified {
            get {
                return this.oppdatertDatoFieldSpecified;
            }
            set {
                this.oppdatertDatoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Bygning", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class BygningType {
        
        private string bygningsnummerField;
        
        private NaeringsgruppeType naeringsgruppeField;
        
        private BygningstypeType bygningstypeField;
        
        private System.Nullable<double> bebygdArealField;
        
        private bool bebygdArealFieldSpecified;
        
        private EtasjeType[] etasjerField;
        
        private AvloepstilknytningType avlopField;
        
        private BruksenhetType[] bruksenheterField;
        
        private EnergiforsyningType energiforsyningField;
        
        private VanntilknytningType vannforsyningField;
        
        private System.Nullable<bool> harHeisField;
        
        private bool harHeisFieldSpecified;
        
        private EndringsstatusType endringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bygningsnummer {
            get {
                return this.bygningsnummerField;
            }
            set {
                this.bygningsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NaeringsgruppeType naeringsgruppe {
            get {
                return this.naeringsgruppeField;
            }
            set {
                this.naeringsgruppeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BygningstypeType bygningstype {
            get {
                return this.bygningstypeField;
            }
            set {
                this.bygningstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bebygdAreal {
            get {
                return this.bebygdArealField;
            }
            set {
                this.bebygdArealField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bebygdArealSpecified {
            get {
                return this.bebygdArealFieldSpecified;
            }
            set {
                this.bebygdArealFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("etasje", IsNullable=false)]
        public EtasjeType[] etasjer {
            get {
                return this.etasjerField;
            }
            set {
                this.etasjerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AvloepstilknytningType avlop {
            get {
                return this.avlopField;
            }
            set {
                this.avlopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("bruksenhet", IsNullable=false)]
        public BruksenhetType[] bruksenheter {
            get {
                return this.bruksenheterField;
            }
            set {
                this.bruksenheterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EnergiforsyningType energiforsyning {
            get {
                return this.energiforsyningField;
            }
            set {
                this.energiforsyningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VanntilknytningType vannforsyning {
            get {
                return this.vannforsyningField;
            }
            set {
                this.vannforsyningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> harHeis {
            get {
                return this.harHeisField;
            }
            set {
                this.harHeisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool harHeisSpecified {
            get {
                return this.harHeisFieldSpecified;
            }
            set {
                this.harHeisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public EndringsstatusType endring {
            get {
                return this.endringField;
            }
            set {
                this.endringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Naeringsgruppe", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class NaeringsgruppeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Bygningstype", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class BygningstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Etasje", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class EtasjeType {
        
        private string antallBoenheterField;
        
        private System.Nullable<double> bruksarealTilAnnetField;
        
        private bool bruksarealTilAnnetFieldSpecified;
        
        private System.Nullable<double> bruksarealTilBoligField;
        
        private bool bruksarealTilBoligFieldSpecified;
        
        private System.Nullable<double> bruksarealTotaltField;
        
        private bool bruksarealTotaltFieldSpecified;
        
        private string etasjenummerField;
        
        private EtasjeplanType etasjeplanField;
        
        private System.Nullable<double> bruttoarealTilBoligField;
        
        private bool bruttoarealTilBoligFieldSpecified;
        
        private System.Nullable<double> bruttoarealTilAnnetField;
        
        private bool bruttoarealTilAnnetFieldSpecified;
        
        private EndringsstatusType endringField;
        
        private System.Nullable<double> bruttoarealTotaltField;
        
        private bool bruttoarealTotaltFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string antallBoenheter {
            get {
                return this.antallBoenheterField;
            }
            set {
                this.antallBoenheterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bruksarealTilAnnet {
            get {
                return this.bruksarealTilAnnetField;
            }
            set {
                this.bruksarealTilAnnetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruksarealTilAnnetSpecified {
            get {
                return this.bruksarealTilAnnetFieldSpecified;
            }
            set {
                this.bruksarealTilAnnetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bruksarealTilBolig {
            get {
                return this.bruksarealTilBoligField;
            }
            set {
                this.bruksarealTilBoligField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruksarealTilBoligSpecified {
            get {
                return this.bruksarealTilBoligFieldSpecified;
            }
            set {
                this.bruksarealTilBoligFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bruksarealTotalt {
            get {
                return this.bruksarealTotaltField;
            }
            set {
                this.bruksarealTotaltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruksarealTotaltSpecified {
            get {
                return this.bruksarealTotaltFieldSpecified;
            }
            set {
                this.bruksarealTotaltFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string etasjenummer {
            get {
                return this.etasjenummerField;
            }
            set {
                this.etasjenummerField = value;
            }
        }
        
        /// <remarks/>
        public EtasjeplanType etasjeplan {
            get {
                return this.etasjeplanField;
            }
            set {
                this.etasjeplanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bruttoarealTilBolig {
            get {
                return this.bruttoarealTilBoligField;
            }
            set {
                this.bruttoarealTilBoligField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruttoarealTilBoligSpecified {
            get {
                return this.bruttoarealTilBoligFieldSpecified;
            }
            set {
                this.bruttoarealTilBoligFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bruttoarealTilAnnet {
            get {
                return this.bruttoarealTilAnnetField;
            }
            set {
                this.bruttoarealTilAnnetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruttoarealTilAnnetSpecified {
            get {
                return this.bruttoarealTilAnnetFieldSpecified;
            }
            set {
                this.bruttoarealTilAnnetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public EndringsstatusType endring {
            get {
                return this.endringField;
            }
            set {
                this.endringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> bruttoarealTotalt {
            get {
                return this.bruttoarealTotaltField;
            }
            set {
                this.bruttoarealTotaltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruttoarealTotaltSpecified {
            get {
                return this.bruttoarealTotaltFieldSpecified;
            }
            set {
                this.bruttoarealTotaltFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Energiforsyning", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class EnergiforsyningType {
        
        private VarmefordelingType[] varmefordelingField;
        
        private EnergiforsyningTypeType[] energiforsyningField;
        
        private System.Nullable<bool> relevantField;
        
        private bool relevantFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("varmefordeling", IsNullable=false)]
        public VarmefordelingType[] varmefordeling {
            get {
                return this.varmefordelingField;
            }
            set {
                this.varmefordelingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("energiforsyningType", IsNullable=false)]
        public EnergiforsyningTypeType[] energiforsyning {
            get {
                return this.energiforsyningField;
            }
            set {
                this.energiforsyningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> relevant {
            get {
                return this.relevantField;
            }
            set {
                this.relevantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool relevantSpecified {
            get {
                return this.relevantFieldSpecified;
            }
            set {
                this.relevantFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Varmefordeling", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class VarmefordelingType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("EnergiforsyningType", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class EnergiforsyningTypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Vanntilknytning", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class VanntilknytningType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Saksnummer", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class SaksnummerType {
        
        private string saksaarField;
        
        private string sakssekvensnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string saksaar {
            get {
                return this.saksaarField;
            }
            set {
                this.saksaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string sakssekvensnummer {
            get {
                return this.sakssekvensnummerField;
            }
            set {
                this.sakssekvensnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Vedtak", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class VedtakType {
        
        private string beskrivelseField;
        
        private System.DateTime vedtaksdatoField;
        
        private VedtakstypeType statusField;
        
        private DispensasjonType[] dispensasjonerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime vedtaksdato {
            get {
                return this.vedtaksdatoField;
            }
            set {
                this.vedtaksdatoField = value;
            }
        }
        
        /// <remarks/>
        public VedtakstypeType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dispensasjon", IsNullable=false)]
        public DispensasjonType[] dispensasjoner {
            get {
                return this.dispensasjonerField;
            }
            set {
                this.dispensasjonerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Vedtakstype", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class VedtakstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Dispensasjon", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class DispensasjonType {
        
        private DispensasjonstypeType dispensasjonstypeField;
        
        private string begrunnelseField;
        
        /// <remarks/>
        public DispensasjonstypeType dispensasjonstype {
            get {
                return this.dispensasjonstypeField;
            }
            set {
                this.dispensasjonstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string begrunnelse {
            get {
                return this.begrunnelseField;
            }
            set {
                this.begrunnelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Dispensasjonstype", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class DispensasjonstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1")]
    [System.Xml.Serialization.XmlRootAttribute("Tiltaktype", Namespace="http://rep.geointegrasjon.no/Matrikkel/foering/v1", IsNullable=false)]
    public partial class TiltaktypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
}
